import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export const languages = ['English', 'Русский', 'Қазақша', 'Español', 'Français', 'Deutsch'] as const;
export type Language = typeof languages[number];

const translations = {
  English: {
    leaders: 'Leaders', tasks: 'Tasks', calendar: 'Calendar', dashboard: 'Dashboard', health: 'Health', settings: 'Settings',
    personalize: 'PERSONALIZE YOUR SPACE', edit: 'Edit', preferences: 'Preferences', appearance: 'Appearance', darkMode: 'Dark mode', lightMode: 'Light mode',
    notifications: 'Notifications', reminders: 'Reminders and daily summary', language: 'Language', chooseLanguage: 'Choose the app language', gender: 'Gender', account: 'Account',
    calendarSync: 'Calendar sync', connectCalendar: 'Connect Google Calendar', privacy: 'Privacy & data', manageInfo: 'Manage your information', signOut: 'Sign out',
    yourDay: 'Your day', todaysTasks: "Today's tasks", weeklyProductivity: 'WEEKLY PRODUCTIVITY', updates: 'Updates as you complete items',
    goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening', topPriority: 'TOP PRIORITY', finished: 'FINISHED', today: 'Today', yesterday: 'Yesterday', tomorrow: 'Tomorrow',
    stayOnTrack: 'STAY ON TRACK', myTasks: 'My tasks', all: 'All', highPriority: 'High priority', addTask: 'Add a task', taskHelp: 'Give your task a clear name and priority.', taskName: 'Task name', taskPlaceholder: 'What needs to be done?', category: 'Category', time: 'Time', priority: 'Priority', low: 'Low', medium: 'Medium', high: 'High', noDueTime: 'No due time', noTasks: 'No tasks yet', openTasks: 'Open Tasks to add your first one.', planYourTime: 'PLAN YOUR TIME', allDay: 'All day', holiday: 'holiday', noEvents: 'No events yet', addToDay: 'Add something to this day', newEvent: 'New event', eventName: 'Event name', eventPlaceholder: 'What’s happening?', planKind: 'What kind of plan is this?', wantToDo: 'Want to do', haveToDo: 'Have to do', addEvent: 'Add event', reminderAtTime: 'Reminder at event time',
    water: 'Glasses of water', habitsDone: 'Habits completed', budgetRemaining: 'Budget remaining', todaysMood: 'Today’s mood', tapUpdate: 'Tap to update', waterTracker: 'Water tracker', waterHelp: 'Keep going—you’re building a healthy rhythm.', glasses: 'glasses', todaysHabits: 'Today’s habits', habitsHelp: 'Tap each habit when you complete it.', addHabit: 'Add your own habit', add: 'Add', firstHabit: 'Add your first habit to begin tracking it.', feeling: 'How are you feeling?', moodHelp: 'Select the mood that best describes today.', gameLabel: 'OFFLINE MINI GAME', playSnake: 'Play Apple Snake', gameBreak: 'Take a quick break and beat your best score.', play: 'Play', score: 'Score', best: 'Best', restart: 'Restart', gameOver: 'Game over', snake: 'Snake', scored: 'You scored {score} points!', snakeHelp: 'Eat apples and avoid the walls.', playAgain: 'Play again', startGame: 'Start game', snakeColor: 'Snake color', gameControls: 'Swipe the board, use the phone buttons, or play with arrow keys and WASD. Your best score is saved on this device.', back: 'Back',
  },
  Русский: {
    leaders: 'Лидеры', tasks: 'Задачи', calendar: 'Календарь', dashboard: 'Главная', health: 'Здоровье', settings: 'Настройки',
    personalize: 'НАСТРОЙТЕ ПРИЛОЖЕНИЕ', edit: 'Изменить', preferences: 'Предпочтения', appearance: 'Оформление', darkMode: 'Тёмная тема', lightMode: 'Светлая тема',
    notifications: 'Уведомления', reminders: 'Напоминания и итоги дня', language: 'Язык', chooseLanguage: 'Выберите язык приложения', gender: 'Пол', account: 'Аккаунт',
    calendarSync: 'Синхронизация календаря', connectCalendar: 'Подключить Google Календарь', privacy: 'Данные и приватность', manageInfo: 'Управление информацией', signOut: 'Выйти',
    yourDay: 'Ваш день', todaysTasks: 'Задачи на сегодня', weeklyProductivity: 'ПРОДУКТИВНОСТЬ ЗА НЕДЕЛЮ', updates: 'Обновляется по мере выполнения',
    goodMorning: 'Доброе утро', goodAfternoon: 'Добрый день', goodEvening: 'Добрый вечер', topPriority: 'ГЛАВНАЯ ЗАДАЧА', finished: 'ГОТОВО', today: 'Сегодня', yesterday: 'Вчера', tomorrow: 'Завтра',
    stayOnTrack: 'НЕ СБИВАЙТЕСЬ С КУРСА', myTasks: 'Мои задачи', all: 'Все', highPriority: 'Высокий приоритет', addTask: 'Добавить задачу', taskHelp: 'Дайте задаче понятное название и приоритет.', taskName: 'Название задачи', taskPlaceholder: 'Что нужно сделать?', category: 'Категория', time: 'Время', priority: 'Приоритет', low: 'Низкий', medium: 'Средний', high: 'Высокий', noDueTime: 'Без срока', noTasks: 'Задач пока нет', openTasks: 'Откройте Задачи и добавьте первую.', planYourTime: 'ПЛАНИРУЙТЕ ВРЕМЯ', allDay: 'Весь день', holiday: 'праздник', noEvents: 'Событий пока нет', addToDay: 'Добавьте событие на этот день', newEvent: 'Новое событие', eventName: 'Название события', eventPlaceholder: 'Что произойдёт?', planKind: 'Какой это план?', wantToDo: 'Хочу сделать', haveToDo: 'Нужно сделать', addEvent: 'Добавить событие', reminderAtTime: 'Напоминание во время события', water: 'Стаканы воды', habitsDone: 'Привычки выполнены', budgetRemaining: 'Остаток бюджета', todaysMood: 'Настроение сегодня', tapUpdate: 'Нажмите, чтобы изменить', waterTracker: 'Учёт воды', waterHelp: 'Продолжайте — вы создаёте полезный ритм.', glasses: 'стаканов', todaysHabits: 'Сегодняшние привычки', habitsHelp: 'Отмечайте каждую выполненную привычку.', addHabit: 'Добавить свою привычку', add: 'Добавить', firstHabit: 'Добавьте первую привычку.', feeling: 'Как вы себя чувствуете?', moodHelp: 'Выберите настроение, которое описывает ваш день.', gameLabel: 'ОФЛАЙН-МИНИ-ИГРА', playSnake: 'Играть в змейку', gameBreak: 'Сделайте перерыв и побейте свой рекорд.', play: 'Играть', score: 'Счёт', best: 'Рекорд', restart: 'Заново', gameOver: 'Игра окончена', snake: 'Змейка', scored: 'Вы набрали {score} очков!', snakeHelp: 'Ешьте яблоки и избегайте стен.', playAgain: 'Играть снова', startGame: 'Начать игру', snakeColor: 'Цвет змейки', gameControls: 'Проведите по полю, используйте кнопки телефона, стрелки или WASD. Рекорд сохраняется на устройстве.', back: 'Назад',
  },
  Қазақша: {
    leaders: 'Көшбасшылар', tasks: 'Тапсырмалар', calendar: 'Күнтізбе', dashboard: 'Басты бет', health: 'Денсаулық', settings: 'Баптаулар',
    personalize: 'ҚОЛДАНБАНЫ БАПТАҢЫЗ', edit: 'Өзгерту', preferences: 'Қалаулар', appearance: 'Көрініс', darkMode: 'Қараңғы режим', lightMode: 'Жарық режим',
    notifications: 'Хабарландырулар', reminders: 'Еске салулар және күн қорытындысы', language: 'Тіл', chooseLanguage: 'Қолданба тілін таңдаңыз', gender: 'Жыныс', account: 'Аккаунт',
    calendarSync: 'Күнтізбені синхрондау', connectCalendar: 'Google Күнтізбесін қосу', privacy: 'Құпиялылық және деректер', manageInfo: 'Ақпаратты басқару', signOut: 'Шығу',
    yourDay: 'Сіздің күніңіз', todaysTasks: 'Бүгінгі тапсырмалар', weeklyProductivity: 'АПТАЛЫҚ ӨНІМДІЛІК', updates: 'Орындалған сайын жаңарады',
    goodMorning: 'Қайырлы таң', goodAfternoon: 'Қайырлы күн', goodEvening: 'Қайырлы кеш', topPriority: 'БАСТЫ МАҚСАТ', finished: 'ДАЙЫН', today: 'Бүгін', yesterday: 'Кеше', tomorrow: 'Ертең',
    stayOnTrack: 'ЖОСПАРДАН ҚАЛМАҢЫЗ', myTasks: 'Менің тапсырмаларым', all: 'Барлығы', highPriority: 'Жоғары басымдық', addTask: 'Тапсырма қосу', taskHelp: 'Тапсырмаға анық атау мен басымдық беріңіз.', taskName: 'Тапсырма атауы', taskPlaceholder: 'Не істеу керек?', category: 'Санат', time: 'Уақыт', priority: 'Басымдық', low: 'Төмен', medium: 'Орташа', high: 'Жоғары', noDueTime: 'Мерзімсіз', noTasks: 'Тапсырмалар жоқ', openTasks: 'Алғашқы тапсырманы Тапсырмалар бөлімінде қосыңыз.', planYourTime: 'УАҚЫТТЫ ЖОСПАРЛАҢЫЗ', allDay: 'Күні бойы', holiday: 'мереке', noEvents: 'Оқиғалар жоқ', addToDay: 'Осы күнге оқиға қосыңыз', newEvent: 'Жаңа оқиға', eventName: 'Оқиға атауы', eventPlaceholder: 'Не болады?', planKind: 'Бұл қандай жоспар?', wantToDo: 'Жасағым келеді', haveToDo: 'Жасауым керек', addEvent: 'Оқиға қосу', reminderAtTime: 'Оқиға уақытында еске салу', water: 'Су стақандары', habitsDone: 'Орындалған әдеттер', budgetRemaining: 'Қалған бюджет', todaysMood: 'Бүгінгі көңіл күй', tapUpdate: 'Өзгерту үшін басыңыз', waterTracker: 'Су есебі', waterHelp: 'Жалғастырыңыз — пайдалы әдет қалыптасып келеді.', glasses: 'стақан', todaysHabits: 'Бүгінгі әдеттер', habitsHelp: 'Орындаған әдетті белгілеңіз.', addHabit: 'Өз әдетіңізді қосыңыз', add: 'Қосу', firstHabit: 'Бірінші әдетіңізді қосыңыз.', feeling: 'Өзіңізді қалай сезінесіз?', moodHelp: 'Бүгінгі көңіл күйіңізді таңдаңыз.', gameLabel: 'ОФЛАЙН ШАҒЫН ОЙЫН', playSnake: 'Жылан ойыны', gameBreak: 'Аздап демалып, рекордыңызды жаңартыңыз.', play: 'Ойнау', score: 'Ұпай', best: 'Рекорд', restart: 'Қайта бастау', gameOver: 'Ойын аяқталды', snake: 'Жылан', scored: 'Сіз {score} ұпай жинадыңыз!', snakeHelp: 'Алманы жеп, қабырғаларға соғылмаңыз.', playAgain: 'Қайта ойнау', startGame: 'Ойынды бастау', snakeColor: 'Жылан түсі', gameControls: 'Алаңда сырғытыңыз, телефон түймелерін, бағыттауыштарды немесе WASD пайдаланыңыз. Рекорд құрылғыда сақталады.', back: 'Артқа',
  },
  Español: {
    leaders: 'Líderes', tasks: 'Tareas', calendar: 'Calendario', dashboard: 'Inicio', health: 'Salud', settings: 'Ajustes',
    personalize: 'PERSONALIZA TU ESPACIO', edit: 'Editar', preferences: 'Preferencias', appearance: 'Apariencia', darkMode: 'Modo oscuro', lightMode: 'Modo claro',
    notifications: 'Notificaciones', reminders: 'Recordatorios y resumen diario', language: 'Idioma', chooseLanguage: 'Elige el idioma', gender: 'Género', account: 'Cuenta',
    calendarSync: 'Sincronizar calendario', connectCalendar: 'Conectar Google Calendar', privacy: 'Privacidad y datos', manageInfo: 'Gestionar tu información', signOut: 'Cerrar sesión',
    yourDay: 'Tu día', todaysTasks: 'Tareas de hoy', weeklyProductivity: 'PRODUCTIVIDAD SEMANAL', updates: 'Se actualiza al completar elementos',
    goodMorning: 'Buenos días', goodAfternoon: 'Buenas tardes', goodEvening: 'Buenas noches', topPriority: 'PRIORIDAD PRINCIPAL', finished: 'TERMINADO', today: 'Hoy', yesterday: 'Ayer', tomorrow: 'Mañana',
    stayOnTrack: 'MANTÉN EL RUMBO', myTasks: 'Mis tareas', all: 'Todas', highPriority: 'Prioridad alta', addTask: 'Añadir tarea', taskHelp: 'Dale un nombre y una prioridad claros.', taskName: 'Nombre de la tarea', taskPlaceholder: '¿Qué hay que hacer?', category: 'Categoría', time: 'Hora', priority: 'Prioridad', low: 'Baja', medium: 'Media', high: 'Alta', noDueTime: 'Sin hora límite', noTasks: 'Aún no hay tareas', openTasks: 'Abre Tareas para añadir la primera.', planYourTime: 'PLANIFICA TU TIEMPO', allDay: 'Todo el día', holiday: 'festivo', noEvents: 'Aún no hay eventos', addToDay: 'Añade algo a este día', newEvent: 'Nuevo evento', eventName: 'Nombre del evento', eventPlaceholder: '¿Qué va a pasar?', planKind: '¿Qué tipo de plan es?', wantToDo: 'Quiero hacerlo', haveToDo: 'Tengo que hacerlo', addEvent: 'Añadir evento', reminderAtTime: 'Recordatorio a la hora del evento', water: 'Vasos de agua', habitsDone: 'Hábitos completados', budgetRemaining: 'Presupuesto restante', todaysMood: 'Estado de ánimo de hoy', tapUpdate: 'Toca para actualizar', waterTracker: 'Control de agua', waterHelp: 'Sigue así: estás creando un ritmo saludable.', glasses: 'vasos', todaysHabits: 'Hábitos de hoy', habitsHelp: 'Toca cada hábito al completarlo.', addHabit: 'Añade tu propio hábito', add: 'Añadir', firstHabit: 'Añade tu primer hábito para comenzar.', feeling: '¿Cómo te sientes?', moodHelp: 'Elige el estado de ánimo que mejor describa hoy.', gameLabel: 'MINIJUEGO SIN CONEXIÓN', playSnake: 'Jugar a la serpiente', gameBreak: 'Tómate un descanso y supera tu récord.', play: 'Jugar', score: 'Puntos', best: 'Récord', restart: 'Reiniciar', gameOver: 'Fin del juego', snake: 'Serpiente', scored: '¡Conseguiste {score} puntos!', snakeHelp: 'Come manzanas y evita las paredes.', playAgain: 'Jugar de nuevo', startGame: 'Iniciar juego', snakeColor: 'Color de la serpiente', gameControls: 'Desliza el tablero, usa los botones del teléfono, las flechas o WASD. Tu récord se guarda en este dispositivo.', back: 'Volver',
  },
  Français: {
    leaders: 'Classement', tasks: 'Tâches', calendar: 'Calendrier', dashboard: 'Accueil', health: 'Santé', settings: 'Réglages',
    personalize: 'PERSONNALISEZ VOTRE ESPACE', edit: 'Modifier', preferences: 'Préférences', appearance: 'Apparence', darkMode: 'Mode sombre', lightMode: 'Mode clair',
    notifications: 'Notifications', reminders: 'Rappels et résumé quotidien', language: 'Langue', chooseLanguage: "Choisir la langue de l’app", gender: 'Genre', account: 'Compte',
    calendarSync: 'Synchronisation calendrier', connectCalendar: 'Connecter Google Agenda', privacy: 'Confidentialité et données', manageInfo: 'Gérer vos informations', signOut: 'Se déconnecter',
    yourDay: 'Votre journée', todaysTasks: "Tâches d’aujourd’hui", weeklyProductivity: 'PRODUCTIVITÉ HEBDOMADAIRE', updates: 'Évolue avec vos tâches terminées',
    goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir', topPriority: 'PRIORITÉ PRINCIPALE', finished: 'TERMINÉ', today: "Aujourd’hui", yesterday: 'Hier', tomorrow: 'Demain',
    stayOnTrack: 'GARDEZ LE CAP', myTasks: 'Mes tâches', all: 'Toutes', highPriority: 'Priorité élevée', addTask: 'Ajouter une tâche', taskHelp: 'Donnez un nom et une priorité clairs.', taskName: 'Nom de la tâche', taskPlaceholder: 'Que faut-il faire ?', category: 'Catégorie', time: 'Heure', priority: 'Priorité', low: 'Faible', medium: 'Moyenne', high: 'Élevée', noDueTime: 'Sans échéance', noTasks: 'Aucune tâche', openTasks: 'Ouvrez Tâches pour ajouter la première.', planYourTime: 'PLANIFIEZ VOTRE TEMPS', allDay: 'Toute la journée', holiday: 'jour férié', noEvents: 'Aucun événement', addToDay: 'Ajoutez quelque chose à cette journée', newEvent: 'Nouvel événement', eventName: 'Nom de l’événement', eventPlaceholder: 'Que se passe-t-il ?', planKind: 'Quel type de projet ?', wantToDo: 'Je veux le faire', haveToDo: 'Je dois le faire', addEvent: 'Ajouter l’événement', reminderAtTime: 'Rappel à l’heure de l’événement', water: 'Verres d’eau', habitsDone: 'Habitudes terminées', budgetRemaining: 'Budget restant', todaysMood: 'Humeur du jour', tapUpdate: 'Touchez pour modifier', waterTracker: 'Suivi de l’eau', waterHelp: 'Continuez : vous créez un rythme sain.', glasses: 'verres', todaysHabits: 'Habitudes du jour', habitsHelp: 'Touchez chaque habitude terminée.', addHabit: 'Ajoutez votre habitude', add: 'Ajouter', firstHabit: 'Ajoutez votre première habitude.', feeling: 'Comment vous sentez-vous ?', moodHelp: 'Choisissez l’humeur qui décrit le mieux votre journée.', gameLabel: 'MINI-JEU HORS LIGNE', playSnake: 'Jouer au serpent', gameBreak: 'Faites une pause et battez votre record.', play: 'Jouer', score: 'Score', best: 'Record', restart: 'Recommencer', gameOver: 'Partie terminée', snake: 'Serpent', scored: 'Vous avez marqué {score} points !', snakeHelp: 'Mangez les pommes et évitez les murs.', playAgain: 'Rejouer', startGame: 'Commencer', snakeColor: 'Couleur du serpent', gameControls: 'Balayez le plateau, utilisez les boutons du téléphone, les flèches ou WASD. Votre record est enregistré sur cet appareil.', back: 'Retour',
  },
  Deutsch: {
    leaders: 'Rangliste', tasks: 'Aufgaben', calendar: 'Kalender', dashboard: 'Übersicht', health: 'Gesundheit', settings: 'Einstellungen',
    personalize: 'DEINEN BEREICH ANPASSEN', edit: 'Bearbeiten', preferences: 'Präferenzen', appearance: 'Darstellung', darkMode: 'Dunkler Modus', lightMode: 'Heller Modus',
    notifications: 'Mitteilungen', reminders: 'Erinnerungen und Tagesübersicht', language: 'Sprache', chooseLanguage: 'App-Sprache auswählen', gender: 'Geschlecht', account: 'Konto',
    calendarSync: 'Kalender synchronisieren', connectCalendar: 'Google Kalender verbinden', privacy: 'Datenschutz & Daten', manageInfo: 'Informationen verwalten', signOut: 'Abmelden',
    yourDay: 'Dein Tag', todaysTasks: 'Heutige Aufgaben', weeklyProductivity: 'WÖCHENTLICHE PRODUKTIVITÄT', updates: 'Aktualisiert sich mit erledigten Aufgaben',
    goodMorning: 'Guten Morgen', goodAfternoon: 'Guten Tag', goodEvening: 'Guten Abend', topPriority: 'HÖCHSTE PRIORITÄT', finished: 'ERLEDIGT', today: 'Heute', yesterday: 'Gestern', tomorrow: 'Morgen',
    stayOnTrack: 'BLEIB DRAN', myTasks: 'Meine Aufgaben', all: 'Alle', highPriority: 'Hohe Priorität', addTask: 'Aufgabe hinzufügen', taskHelp: 'Gib deiner Aufgabe einen klaren Namen und eine Priorität.', taskName: 'Aufgabenname', taskPlaceholder: 'Was muss erledigt werden?', category: 'Kategorie', time: 'Zeit', priority: 'Priorität', low: 'Niedrig', medium: 'Mittel', high: 'Hoch', noDueTime: 'Keine Fälligkeit', noTasks: 'Noch keine Aufgaben', openTasks: 'Öffne Aufgaben und füge deine erste hinzu.', planYourTime: 'PLANE DEINE ZEIT', allDay: 'Ganztägig', holiday: 'Feiertag', noEvents: 'Noch keine Termine', addToDay: 'Füge diesem Tag etwas hinzu', newEvent: 'Neuer Termin', eventName: 'Terminname', eventPlaceholder: 'Was passiert?', planKind: 'Was für ein Plan ist das?', wantToDo: 'Möchte ich tun', haveToDo: 'Muss ich tun', addEvent: 'Termin hinzufügen', reminderAtTime: 'Erinnerung zur Terminzeit', water: 'Gläser Wasser', habitsDone: 'Erledigte Gewohnheiten', budgetRemaining: 'Verbleibendes Budget', todaysMood: 'Heutige Stimmung', tapUpdate: 'Zum Ändern tippen', waterTracker: 'Wasser-Tracker', waterHelp: 'Weiter so – du entwickelst einen gesunden Rhythmus.', glasses: 'Gläser', todaysHabits: 'Heutige Gewohnheiten', habitsHelp: 'Tippe jede erledigte Gewohnheit an.', addHabit: 'Eigene Gewohnheit hinzufügen', add: 'Hinzufügen', firstHabit: 'Füge deine erste Gewohnheit hinzu.', feeling: 'Wie fühlst du dich?', moodHelp: 'Wähle die Stimmung, die den heutigen Tag beschreibt.', gameLabel: 'OFFLINE-MINISPIEL', playSnake: 'Apfel-Schlange spielen', gameBreak: 'Mach kurz Pause und schlag deinen Rekord.', play: 'Spielen', score: 'Punkte', best: 'Rekord', restart: 'Neustart', gameOver: 'Spiel vorbei', snake: 'Schlange', scored: 'Du hast {score} Punkte erzielt!', snakeHelp: 'Iss Äpfel und meide die Wände.', playAgain: 'Nochmal spielen', startGame: 'Spiel starten', snakeColor: 'Schlangenfarbe', gameControls: 'Wische über das Feld oder nutze Handytasten, Pfeiltasten oder WASD. Dein Rekord wird auf diesem Gerät gespeichert.', back: 'Zurück',
  },
} as const;

type TranslationKey = keyof typeof translations.English;
type I18nContextValue = { language: Language; setLanguage: (value: Language) => void; t: (key: TranslationKey) => string };
const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('smart-life-language');
    return languages.includes(saved as Language) ? saved as Language : 'English';
  });

  function setLanguage(value: Language) {
    localStorage.setItem('smart-life-language', value);
    setLanguageState(value);
  }

  useEffect(() => { document.documentElement.lang = localeForLanguage(language); }, [language]);
  return <I18nContext.Provider value={{ language, setLanguage, t: (key) => translations[language][key] }}>{children}</I18nContext.Provider>;
}

export function localeForLanguage(language: Language) {
  return { English: 'en', Русский: 'ru', Қазақша: 'kk', Español: 'es', Français: 'fr', Deutsch: 'de' }[language];
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error('useI18n must be used inside I18nProvider');
  return context;
}
