import type { Language } from './i18n';

type Copy = {
  welcome: string; headline: string; intro: string; quickStart: string; describe: string; healthNote: string; continue: string; private: string;
  features: Array<[string, string]>; genders: [string, string, string, string]; login: string; register: string; loginTitle: string; signupTitle: string;
  authSubtitle: string; google: string; emailDivider: string; email: string; password: string; wait: string; signIn: string; create: string;
  newAccount: string; existingAccount: string; terms: string;
};

export const onboardingCopy: Record<Language, Copy> = {
  English: {
    welcome: 'WELCOME TO SMART AXIS', headline: 'One calm place for your day and wellbeing.', intro: 'Plan tasks, check your calendar, talk with your AI helper, and understand your health without the clutter.', quickStart: 'A QUICK START', describe: 'How would you describe yourself?', healthNote: 'This only personalizes health features.', continue: 'Continue to sign in', private: 'Your choice stays private on this device.',
    features: [['Stay organized', 'Tasks and calendar together.'], ['Know your rhythm', 'Health, nutrition, and daily habits.'], ['Get thoughtful help', 'Your AI assistant is ready when you need it.']], genders: ['Female', 'Male', 'Non-binary', 'Prefer not to say'], login: 'Log in', register: 'Register', loginTitle: 'Log in to Smart Axis', signupTitle: 'Create your account', authSubtitle: 'Your tasks, health, calendar, and daily plans in one calm place.', google: 'Continue with Google', emailDivider: 'or continue with email', email: 'Email address', password: 'Password', wait: 'Please wait…', signIn: 'Sign in', create: 'Create account', newAccount: 'New to Smart Axis? Create an account', existingAccount: 'Already have an account? Sign in', terms: 'By continuing, you agree to securely authenticate through Supabase.',
  },
  Русский: {
    welcome: 'ДОБРО ПОЖАЛОВАТЬ В SMART AXIS', headline: 'Спокойное место для ваших дел и самочувствия.', intro: 'Планируйте задачи, проверяйте календарь, общайтесь с ИИ-помощником и следите за здоровьем.', quickStart: 'БЫСТРЫЙ СТАРТ', describe: 'Как вы себя описываете?', healthNote: 'Это нужно только для настройки функций здоровья.', continue: 'Перейти ко входу', private: 'Ваш выбор хранится только на этом устройстве.',
    features: [['Будьте организованны', 'Задачи и календарь вместе.'], ['Понимайте свой ритм', 'Здоровье, питание и привычки.'], ['Получайте поддержку', 'ИИ-помощник всегда рядом.']], genders: ['Женский', 'Мужской', 'Небинарный', 'Не указывать'], login: 'Войти', register: 'Регистрация', loginTitle: 'Войти в Smart Axis', signupTitle: 'Создать аккаунт', authSubtitle: 'Задачи, здоровье, календарь и планы в одном месте.', google: 'Продолжить с Google', emailDivider: 'или войти по почте', email: 'Электронная почта', password: 'Пароль', wait: 'Подождите…', signIn: 'Войти', create: 'Создать аккаунт', newAccount: 'Нет аккаунта? Зарегистрироваться', existingAccount: 'Уже есть аккаунт? Войти', terms: 'Продолжая, вы используете безопасную авторизацию Supabase.',
  },
  Қазақша: {
    welcome: 'SMART AXIS-ҚА ҚОШ КЕЛДІҢІЗ', headline: 'Күнделікті істер мен көңіл күйге арналған тыныш орын.', intro: 'Тапсырмаларды жоспарлаңыз, күнтізбені қараңыз, AI көмекшісімен сөйлесіңіз және денсаулықты бақылаңыз.', quickStart: 'ЖЫЛДАМ БАСТАУ', describe: 'Өзіңізді қалай сипаттайсыз?', healthNote: 'Бұл тек денсаулық мүмкіндіктерін баптау үшін қажет.', continue: 'Кіруге өту', private: 'Таңдауыңыз тек осы құрылғыда сақталады.',
    features: [['Жоспарлы болыңыз', 'Тапсырмалар мен күнтізбе бірге.'], ['Өз ырғағыңызды біліңіз', 'Денсаулық, тамақтану және әдеттер.'], ['Ойлы көмек алыңыз', 'AI көмекшісі әрқашан дайын.']], genders: ['Әйел', 'Ер', 'Бинарлы емес', 'Айтпауды қалаймын'], login: 'Кіру', register: 'Тіркелу', loginTitle: 'Smart Axis-қа кіру', signupTitle: 'Аккаунт жасау', authSubtitle: 'Тапсырмалар, денсаулық, күнтізбе және жоспарлар бір жерде.', google: 'Google арқылы жалғастыру', emailDivider: 'немесе email арқылы', email: 'Электрондық пошта', password: 'Құпиясөз', wait: 'Күте тұрыңыз…', signIn: 'Кіру', create: 'Аккаунт жасау', newAccount: 'Аккаунтыңыз жоқ па? Тіркеліңіз', existingAccount: 'Аккаунтыңыз бар ма? Кіріңіз', terms: 'Жалғастыру арқылы Supabase қауіпсіз авторизациясын қолданасыз.',
  },
  Español: {
    welcome: 'BIENVENIDO A SMART AXIS', headline: 'Un lugar tranquilo para tu día y bienestar.', intro: 'Planifica tareas, consulta tu calendario, habla con tu asistente de IA y cuida tu salud.', quickStart: 'INICIO RÁPIDO', describe: '¿Cómo te describirías?', healthNote: 'Esto solo personaliza las funciones de salud.', continue: 'Continuar para iniciar sesión', private: 'Tu elección permanece privada en este dispositivo.', features: [['Organízate', 'Tareas y calendario juntos.'], ['Conoce tu ritmo', 'Salud, nutrición y hábitos.'], ['Recibe ayuda', 'Tu asistente de IA está disponible.']], genders: ['Mujer', 'Hombre', 'No binario', 'Prefiero no decirlo'], login: 'Entrar', register: 'Registrarse', loginTitle: 'Entrar en Smart Axis', signupTitle: 'Crea tu cuenta', authSubtitle: 'Tareas, salud, calendario y planes en un lugar tranquilo.', google: 'Continuar con Google', emailDivider: 'o continuar con correo', email: 'Correo electrónico', password: 'Contraseña', wait: 'Espera…', signIn: 'Entrar', create: 'Crear cuenta', newAccount: '¿Nuevo en Smart Axis? Crea una cuenta', existingAccount: '¿Ya tienes cuenta? Entra', terms: 'Al continuar, aceptas autenticarte de forma segura mediante Supabase.',
  },
  Français: {
    welcome: 'BIENVENUE SUR SMART AXIS', headline: 'Un espace calme pour votre journée et votre bien-être.', intro: 'Planifiez vos tâches, consultez le calendrier, parlez à votre assistant IA et suivez votre santé.', quickStart: 'DÉMARRAGE RAPIDE', describe: 'Comment vous décririez-vous ?', healthNote: 'Cela personnalise uniquement les fonctions de santé.', continue: 'Continuer vers la connexion', private: 'Votre choix reste privé sur cet appareil.', features: [['Restez organisé', 'Tâches et calendrier réunis.'], ['Comprenez votre rythme', 'Santé, nutrition et habitudes.'], ['Recevez de l’aide', 'Votre assistant IA est disponible.']], genders: ['Femme', 'Homme', 'Non binaire', 'Préfère ne pas répondre'], login: 'Connexion', register: 'Inscription', loginTitle: 'Se connecter à Smart Axis', signupTitle: 'Créer votre compte', authSubtitle: 'Tâches, santé, calendrier et projets dans un espace calme.', google: 'Continuer avec Google', emailDivider: 'ou continuer par e-mail', email: 'Adresse e-mail', password: 'Mot de passe', wait: 'Veuillez patienter…', signIn: 'Se connecter', create: 'Créer le compte', newAccount: 'Nouveau sur Smart Axis ? Créez un compte', existingAccount: 'Vous avez déjà un compte ? Connectez-vous', terms: 'En continuant, vous utilisez l’authentification sécurisée Supabase.',
  },
  Deutsch: {
    welcome: 'WILLKOMMEN BEI SMART AXIS', headline: 'Ein ruhiger Ort für deinen Tag und dein Wohlbefinden.', intro: 'Plane Aufgaben, prüfe den Kalender, sprich mit deinem KI-Assistenten und achte auf deine Gesundheit.', quickStart: 'SCHNELLSTART', describe: 'Wie würdest du dich beschreiben?', healthNote: 'Dies passt nur die Gesundheitsfunktionen an.', continue: 'Weiter zur Anmeldung', private: 'Deine Auswahl bleibt auf diesem Gerät privat.', features: [['Bleib organisiert', 'Aufgaben und Kalender zusammen.'], ['Verstehe deinen Rhythmus', 'Gesundheit, Ernährung und Gewohnheiten.'], ['Erhalte Hilfe', 'Dein KI-Assistent ist bereit.']], genders: ['Weiblich', 'Männlich', 'Nicht-binär', 'Keine Angabe'], login: 'Anmelden', register: 'Registrieren', loginTitle: 'Bei Smart Axis anmelden', signupTitle: 'Konto erstellen', authSubtitle: 'Aufgaben, Gesundheit, Kalender und Pläne an einem ruhigen Ort.', google: 'Mit Google fortfahren', emailDivider: 'oder mit E-Mail fortfahren', email: 'E-Mail-Adresse', password: 'Passwort', wait: 'Bitte warten…', signIn: 'Anmelden', create: 'Konto erstellen', newAccount: 'Neu bei Smart Axis? Konto erstellen', existingAccount: 'Bereits registriert? Anmelden', terms: 'Wenn du fortfährst, nutzt du die sichere Supabase-Anmeldung.',
  },
};
